apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: devops
  name: techtrends
  namespace: sandbox
spec:
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 3111
    nodePort: 30007
  selector:
    app: techtrends
    tag: devops
  type: ClusterIP
